#include "midi_service.hpp"

#include <app/settings.hpp>

#include <util/stdio_suppress.hpp>
#include <ymir/util/dev_log.hpp>

#include <unordered_set>
#include <vector>

#if defined(YMIR_MIDI_ASYNC_INIT)
    #include <thread>
#endif

namespace app::services {

namespace grp {
    struct midi {
        static constexpr bool enabled = true;
        static constexpr devlog::Level level = devlog::level::debug;
        static constexpr std::string_view name = "MIDI";
    };
} // namespace grp

MIDIService::MIDIService(util::ServiceLocator &serviceLocator)
    : m_serviceLocator(serviceLocator) {

    m_input = std::make_shared<util::RtMidiInNoop>();
    m_output = std::make_shared<util::RtMidiOutNoop>();
}

MIDIService::~MIDIService() = default;

void MIDIService::Initialize(std::function<void()> onComplete) {
    devlog::info<grp::midi>("Initializing MIDI backend...");

#if defined(YMIR_MIDI_ASYNC_INIT)
    // Initialize in a thread because it can take a *long* time to load on some systems...
    // 20 minutes is not unheard of!
    std::thread initThread{[&, onComplete = onComplete] { DoInit(onComplete); }};
    initThread.detach();
#else
    DoInit(onComplete);
#endif
}

std::string MIDIService::GetMidiVirtualInputPortName() const {
    return "Ymir Virtual MIDI Input";
}

std::string MIDIService::GetMidiVirtualOutputPortName() const {
    return "Ymir Virtual MIDI Output";
}

using MidiPortType = Settings::Audio::MidiPort::Type;

std::string MIDIService::GetMidiInputPortName() const {
    auto &settings = m_serviceLocator.GetRequired<Settings>();

    switch (settings.audio.midiInputPort.Get().type) {
    case MidiPortType::None: return "None";
    case MidiPortType::Normal: return settings.audio.midiInputPort.Get().id;
    case MidiPortType::Virtual: return GetMidiVirtualInputPortName();
    }

    return {};
}

std::string MIDIService::GetMidiOutputPortName() const {
    auto &settings = m_serviceLocator.GetRequired<Settings>();

    switch (settings.audio.midiOutputPort.Get().type) {
    case MidiPortType::None: return "None";
    case MidiPortType::Normal: return settings.audio.midiOutputPort.Get().id;
    case MidiPortType::Virtual: return GetMidiVirtualInputPortName();
    }

    return {};
}

int MIDIService::FindInputPortByName(std::string name) const {
    auto input = GetInput();
    unsigned int portCount = input->getPortCount();
    for (unsigned int i = 0; i < portCount; i++) {
        if (input->getPortName(i) == name) {
            return i;
        }
    }

    return -1;
}

int MIDIService::FindOutputPortByName(std::string name) const {
    auto output = GetOutput();
    unsigned int portCount = output->getPortCount();
    for (unsigned int i = 0; i < portCount; i++) {
        if (output->getPortName(i) == name) {
            return i;
        }
    }

    return -1;
}

std::shared_ptr<util::IRtMidiIn> MIDIService::GetInput() const {
#if defined(YMIR_MIDI_ASYNC_INIT)
    return m_input.load(std::memory_order_acquire);
#else
    return m_input;
#endif
}

std::shared_ptr<util::IRtMidiOut> MIDIService::GetOutput() const {
#if defined(YMIR_MIDI_ASYNC_INIT)
    return m_output.load(std::memory_order_acquire);
#else
    return m_output;
#endif
}

void MIDIService::SetInput(std::shared_ptr<util::IRtMidiIn> input) {
#if defined(YMIR_MIDI_ASYNC_INIT)
    m_input.store(input, std::memory_order_release);
#else
    m_input = input;
#endif
}

void MIDIService::SetOutput(std::shared_ptr<util::IRtMidiOut> output) {
#if defined(YMIR_MIDI_ASYNC_INIT)
    m_output.store(output, std::memory_order_release);
#else
    m_output = output;
#endif
}

void MIDIService::SetMidiInputCallback(RtMidiIn::RtMidiCallback callback, void *userData) {
    std::unique_lock lock{m_mtxCallback};
    auto input = GetInput();
    input->setCallback(callback, userData);
    m_inputCallback = callback;
    m_inputCallbackUserData = userData;
}

void MIDIService::DoInit(std::function<void()> onComplete) {
    std::vector<RtMidi::Api> apis{};
    std::unordered_set<RtMidi::Api> failedAPIs{};
    RtMidi::getCompiledApi(apis);
    auto makeRtMidi = [&]<typename T>(const char *name) -> std::unique_ptr<T> {
        for (auto api : apis) {
            if (failedAPIs.contains(api)) {
                continue;
            }
            try {
                return std::make_unique<T>(api, name);
            } catch (const RtMidiError &) {
                // just ignore it and try the next API
                failedAPIs.insert(api);
            }
        }
        return {};
    };

    // Suppress warnings generated by RtMidi during instantiation
    {
        util::StdErrSuppressor suppressor{};

        auto input = util::WrapRtMidi(makeRtMidi.operator()<RtMidiIn>("Ymir MIDI input client"));
        auto output = util::WrapRtMidi(makeRtMidi.operator()<RtMidiOut>("Ymir MIDI output client"));
        input->ignoreTypes(false, false, false);
        input->setCallback(m_inputCallback, m_inputCallbackUserData);
        const std::string api = input->getApiName(input->getCurrentApi());
        devlog::info<grp::midi>("Using MIDI backend: {}", api);

        std::unique_lock lock{m_mtxCallback};
        SetInput(input);
        SetOutput(output);
    }
}

} // namespace app::services
