void runVDP1PolygonSandbox();
void runBUPSandbox();
void runInputSandbox();
void runVDP1AccuracySandbox(int argc, char **argv);
void runBinCueLoaderSandbox(int argc, char **argv);
void runCurlSandbox();
void runSH2PerfSandbox();
void runDiscInfoExtractor(int argc, char **argv);
void runDeadlockTest(int argc, char **argv);
void runHostCDSandbox();
